postgres:
  host: postgres-db
  port: 5432
  database: kdcube
  ssl: "False"

existingPostgresSecret:
  name: postgres-db-credentials
  userKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

bootstrap:
  tenantId: TENANT_ID
  projectId: PROJECT_ID
