apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
data:
  config.json: |
    {
      "auth": {
        "authType": "hardcoded",
        "token": "test-admin-token-123"
      },
      "tenant": "TENANT_ID",
      "project": "PROJECT_ID",
      "routesPrefix": "/chatbot"
    }
