{{- if .Values.secrets.platform.create }}
{{- $openai := .Values.secrets.platform.data.OPENAI_API_KEY | default .Values.services.openai.api_key | default "" -}}
{{- $hf := .Values.secrets.platform.data.HUGGING_FACE_API_TOKEN | default .Values.services.huggingface.api_key | default "" -}}
{{- $anthropic := .Values.secrets.platform.data.ANTHROPIC_API_KEY | default .Values.services.anthropic.api_key | default "" -}}
{{- $brave := .Values.secrets.platform.data.BRAVE_API_KEY | default .Values.services.brave.api_key | default "" -}}
{{- $awsAccessKey := .Values.aws.access_key_id | default "" -}}
{{- $awsSecretKey := .Values.aws.secret_access_key | default "" -}}
{{- $adminToken := .Values.secrets.platform.data.SECRETS_ADMIN_TOKEN | default "" -}}
{{- $readTokens := .Values.secrets.platform.data.SECRETS_READ_TOKENS | default "" -}}
{{- $tokenIngress := .Values.secrets.platform.data.SECRETS_TOKEN_INGRESS | default "" -}}
{{- $tokenProc := .Values.secrets.platform.data.SECRETS_TOKEN_PROC | default "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.platform.name }}
  labels:
    app.kubernetes.io/name: {{ include "kdcube-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ $openai | quote }}
  HUGGING_FACE_API_TOKEN: {{ $hf | quote }}
  ANTHROPIC_API_KEY: {{ $anthropic | quote }}
  BRAVE_API_KEY: {{ $brave | quote }}
  AWS_ACCESS_KEY_ID: {{ $awsAccessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $awsSecretKey | quote }}
  SECRETS_ADMIN_TOKEN: {{ $adminToken | quote }}
  SECRETS_READ_TOKENS: {{ $readTokens | quote }}
  SECRETS_TOKEN_INGRESS: {{ $tokenIngress | quote }}
  SECRETS_TOKEN_PROC: {{ $tokenProc | quote }}
{{- end }}
