FROM openresty/openresty:alpine

# Build argument for nginx config path (relative to build context)
ARG NGINX_CONFIG_FILE_PATH

# Copy nginx configuration from customer repo
COPY ${NGINX_CONFIG_FILE_PATH} /usr/local/openresty/nginx/conf/nginx.conf

# Create webroot for Let's Encrypt
# RUN mkdir -p /var/www/letsencrypt

# EXPOSE 80 443
EXPOSE 80

CMD ["openresty", "-g", "daemon off;"]