{{- if .Values.auth.enabled }}
{{- $redisPassword := default .Values.auth.password .Values.infra.redis.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  redis-password: {{ $redisPassword | quote }}
{{- end }}
