apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres-db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "postgres-db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
